### ISSUE TITLE
Create a zombie infection simulation

### ISSUE THREAD

**Issue by Ellzord** [Ellzord/JALSE#107]
Simple virus spreading simulation:
- Create a number of people
- Create very few infected
- Infected move faster than people
- When an infected touches a person that person becomes infected
- When infection starts it takes some time to be infected (should change colour)

**Comment by wlmiller** [comment]
I'd be interested in taking this one if no one else is on it.  Should I make a new repo for it and then transfer ownership?

**Comment by Ellzord** [comment]
Yeah you can take it. Yeah I think that would be the best approach (after transfer you should keep contributor rights encase you wish to maintain/enhance it).

What are your thoughts on the implementation?

**Comment by wlmiller** [comment]
I was thinking it could be a perfect application for #101.

Basically, when a person is infected, they change to a transitional type, and the `EntityListener` schedules them for an action that gradually changes their color and eventually changes their type to `Infected`.  

When they change type to `Infected`, they could undergo whatever changes they need to undergo, e.g. increase their speed, make them move toward people instead of away from zombies, etc.

**Comment by Ellzord** [comment]
I think you're right about #101 (so I updated that issue to contain what I thought it should be like - can you check it over?).

This is definitely the right way to go about the logic! Possible additions: `Infected` will die after X time/steps without infecting another and you can maybe add some sliders for amount of starting `Infected`, total population (not infected) and maybe population density.

The above additions will probably depend on how complex the model is. Sounds like you have it covered!

**Comment by Ellzord** [comment]
As of release v1.0.7 (on central) there is `EntityTypeListener`  and I've updated the [wiki here](https://github.com/Ellzord/JALSE/wiki/Creating-an-EntityTypeListener)

Should be good to go!

**Comment by wlmiller** [comment]
I think this is basically ready for a look: https://github.com/wlmiller/JALSE-Zombies

It's kind of fun to play with the different sliders.

**Comment by Ellzord** [comment]
Just gave it a look and a run up it's **awesome**! Definitely the coolest example we have right now.

How was it to make? Easy, challenging, frustrating? Do you think the core is missing anything to make life a bit easier?

Really impressed by this (and others who watch the repo have said so too)!

**Comment by wlmiller** [comment]
Thanks a lot!  Honestly it all came together pretty easily.

There were a couple of things that the entity type model made things more frustrating than I expected:
1. It's not easy to get the type(s) an entity is marked as.  When I was experimenting with it, the best way I found was to have a type `Attribute`, and use the entity type listener to set the attribute, which works, but was a little cumbersome.
2. It would be nice to have some type of `unmarkAsAllTypes()` method on entities, but this wasn't a big deal.
3. I would have like to have put the method that chooses which direction a person will move as a default method on the respective types - so e.g. `Person.direction`, `Healthy.direction`, `Infected.direction`, but every way I tried to make this work (I think I tried using `Entity.asType()` as well as setting an attribute as mentioned above) was really, really slow, so I ended up just throwing those methods together and giving the entities a `Method` attribute pointing to the appropriate one.

But overall the listeners and actions made it pretty easy to just sort of wire everything up and let it go.

**Comment by Ellzord** [comment]
Great that it went pretty smoothly!
1. So what would you recommend? I added `getMarkedTypes()` for the entity listener changes.
2. I think that is a good method to add and I will also rename `getMarkedTypes()` to `getMarkedAsTypes()`!
3. I have run into this issue before. The `unreflectSpecial` of `default` methods on proxies is incredibly slow and it's not something we can fix ourselves (we should raise with JDK really). I think that if we addressed 1 (or used another `Action` to generate the Direction and put it on the `Entity` in a chain `MultiAction`) we could get around this.

Let me know your thoughts

**Comment by Ellzord** [comment]
https://github.com/Ellzord/JALSE/pull/136

Gave this some more thought: I will add `streamMarkedAsTypes()` as well.

As for `default` methods I think we could add caching to the `unreflectSpecial` per proxy but I will do a performance test to see if that is the real issue. If that is the main performance problem (and not the `invoke`) then since we already cache the proxies per type it'll only be the first call that is slow and we can uncache when the proxy gets uncached. We may have to write it directly into the `DefaultEntityProxyFactory` but that would be fine as long as if the `MethodFunction` was there it would override it.

Then you could just get the type like `streamMarkedAsTypes().filter(t -> !Person.class.equals(t)).getFirst().get()` and then do the `default` method as normal.

#137

**Comment by Ellzord** [comment]
Or of course alot of `if`s or a `switch` in a  `for` loop.

**Comment by Ellzord** [comment]
I have done some research here see this [gist](https://gist.github.com/Ellzord/072813c8bc5e34d56dd1) (I know its not properly benchmarked). It looks if we cache the method handle and not the we cut out over half the time but it's still much slower.

I was playing with `MethodHandle` and found I could get it to be quicker than regular reflection if I knew upfront what I wanted to do

```
unflectSpecial 0ms (42299ns) ignore 0ms (311ns) invokeExact 0ms (622ns) Total 0ms (43232ns)
unflectSpecial 0ms (43232ns) ignore 0ms (311ns) invokeExact 0ms (622ns) Total 0ms (44165ns)
```

The `622ns` can be optimised further with caching the handle (JIT)!
NOTE: it took `~2000ns` for each regular `Method.invoke()` on an each impl. 

So it looks like there are some real optimisation to be done for the `EntityProxyFactory` system we currently use - I think I will will jump on this.

**Comment by wlmiller** [comment]
For 1 and 2, I think the things you suggested are good fixes, and shouldn't be hard to implement.  For 3, it was more of an observation - the type system doesn't lend itself to that type of inheritance, so my mental model of how I thought I would implement it didn't work in practice.

**Comment by Ellzord** [comment]
Cool - 1 and 2 I pushed a changed for already (including `streamMarkedAsTypes()`) so I will do a release shortly but you can use 1.0.8-SNAPSHOT until then. The `MultiActionBuilder` should help with generating the direction up front then they're uniformly processed via an action chain.

As for the performance concerns I have actually met these before and I think they're quite important really. Otherwise we're forcing our users to entirely use bean-like structures because JALSE can't handle any logic on a type (and requires a controller/helper/action class per type). I do think the action chain is a good approach for the Zombies simulation though. So I will do some changes around `default` methods (especially as private defaults are coming in Java 9).

Probably shouldn't be in this ticket but I'd like to come up with a roadmap for JALSE (what we should do next, focus on, move towards in the future, etc). Do you think you could gitter/email me your thoughts?

**Comment by Ellzord** [comment]
@wlmiller Great work!
