### ISSUE TITLE
Create Robomop simulation

### ISSUE THREAD

**Issue by Ellzord** [Ellzord/JALSE#57]
Very simple roomba-like simulation:
1. Mop goes until it hits wall
2. Mop rotates randomly degrees
3. Repeat 1

The mop will eventually clean the floor.. Eventually..

NOTE: This should be visual and runnable via [WebStart](https://docs.oracle.com/javase/tutorial/deployment/webstart/deploying.html)

**Comment by hwride** [comment]
My attempt at a simple JALSE RoboMop: https://github.com/hwride/jalse-robomop. There's no WebStart though, just console logging of the room.

I considered making Room an entity but wasn't sure about that...

**Comment by Ellzord** [comment]
Just had a look at your project - looks really good.

With regards to making `Room` an `Entity` this would be good if you wanted to easily scale to a multi-room mop simulation (which I think is overkill for a simple example). I think you made the right decision there.

I did notice a few things that could be addressed:
- You need to set the maven source compliance to 1.8 (seems to be defaulting to 1.5 when importing to eclipse). Ideally this would be gradle + wrapper anyway like [HappyCows](https://github.com/Ellzord/JALSE-HappyCows) but I can do this later.
- Your simulation actually supports multiple mops and you iterate through all the mops in your JALSE instance. If you only want one mop I'd suggest you move the `MoveRoboMop` to the mop and then just do `context.getActor().asType(RoboMop.class)` then you don't have to iterate through them all (same with `Room`).
- This isn't on you but I've uploaded 1.0.5 (24/05/2015) with the entity annotation improvements which can be utilised by your example (not required). When I finished #101 #110 #111 I'll go through and update the examples since it'd be quite a difference then.

For everyone else here is some sample output:

```
RoboMop trying to move to x: 3.3149877984387444, y: 3.726662277090713
RoboMop moved to - x: 3.3149877984387444, y: 3.726662277090713
The floor is dirty.
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][ ][X][ ]
[X][ ][ ][R][ ]

RoboMop trying to move to x: 2.437997352546067, y: 3.246154464653742
RoboMop moved to - x: 2.437997352546067, y: 3.246154464653742
The floor is dirty.
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][R][X][ ]
[X][ ][ ][ ][ ]

RoboMop trying to move to x: 1.56100690665339, y: 2.7656466522167706
RoboMop moved to - x: 1.56100690665339, y: 2.7656466522167706
The floor is dirty.
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][R][X][ ]
[X][ ][ ][ ][ ]

RoboMop trying to move to x: 0.684016460760713, y: 2.2851388397797994
RoboMop moved to - x: 0.684016460760713, y: 2.2851388397797994
The floor is dirty.
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][R][ ][ ][ ]
[ ][ ][ ][X][ ]
[X][ ][ ][ ][ ]
```

Overall it looks great! Did you run into any problems using JALSE?

**Comment by hwride** [comment]
Added source and target config for 1.8 to the pom.

To only use a single RoboMop I'm guessing in Main that would be replacing 

``` javascript
jalse.scheduleForActor(new MoveRoboMop(), 0, MS_BETWEEN_MOVES, TimeUnit.MILLISECONDS);
```

with

``` javascript
roboMop.scheduleForActor(new MoveRoboMop(), 0, MS_BETWEEN_MOVES, TimeUnit.MILLISECONDS);
```

And what would be the Jalsey way for room to get access to the RoboMop? Or should it just be passed in as a constructor arg?

One thing that threw me for a bit was realising primitive types were not allowed on an entity. The error message said "Entity type is invalid" and I had to dig into the validation code before I saw the problem.
The JALSE docs were good though and I used HappyCows as a reference which was useful.

**Comment by Ellzord** [comment]
Yeah you could just pass it in or give it the ID of the mop.

Yeah there was a big effort (4k lines worth) added to entity annotations to make them easier to use. I think I'm also going to add some better `context` stuff to `ActionScheduler`. I'm also considering adding primitives back in but the issue is if they have never been set a value its not 100% obvious that it'll give you a null pointer on access.

The coupling between`Room` and `RoboMop` could be made into a one way direction. That would suit the JALSE model better.

By end of next week I hope to have a load of "just realised this is hard to use" changes in! I'll keep you in the know.

**Comment by Ellzord** [comment]
Looking to also create a graphical version of this too!
