### ISSUE TITLE
Investigate moving from Ant to Maven

### ISSUE THREAD

**Issue by Ellzord** [Ellzord/JALSE#62]
Pros:
- Easier to distribute
- Easier to build
- Easier to automate testing

Cons:
- Better to host on github for rapid changes (awkward branching)

See: https://github.com/github/maven-plugins

NOTE: Examples and README.md would require updates.

**Comment by benwaffle** [comment]
what about gradle or sbt

**Comment by Ellzord** [comment]
Had a look at both of them and sbt seems to be in it's infancy somewhat still (which is okay but for easy use with Travis-CI not so great) - Gradle however is going up on the list!

`ant.importBuild 'build.xml'` could be the short-term quite easily!

Also see: http://gradle.org/docs/current/userguide/maven_plugin.html If you ever wanted to use a maven repo for distribution. 

@benwaffle http://docs.travis-ci.com/user/languages/java/

**Comment by pbremer** [comment]
Personally, I am a huge fan of Maven and I am all for migrating. I also see that there is another issue of changing the project structure and that will go hand in hand for maven. Most (but not all) maven projects are structured like src/main/java etc...

**Comment by Ellzord** [comment]
#64 I just made that funnily enough!

**Comment by Ellzord** [comment]
@benwaffle @pbremer https://travis-ci.org/Ellzord/JALSE/builds/61678253

**Comment by Ellzord** [comment]
EDIT: https://issues.sonatype.org/browse/OSSRH-15455
