### ISSUE TITLE
Should we be using GerritHub?

### ISSUE THREAD

**Issue by Ellzord** [Ellzord/JALSE#73]
https://review.gerrithub.io/#/q/project:Ellzord/JALSE

**Comment by Ellzord** [comment]
@benwaffle @pbremer @stelioskiayias @mariosk89 @ckerr89

**Comment by Ellzord** [comment]
Turns out you can just comment in the commit of the pull request - Ignore this!

**Comment by playground** [comment]
How is GerritHub working for you?

**Comment by Ellzord** [comment]
@playground After a few reviews I ended up ditching it. I've used Gerrit a lot professionally and I love it (especially the latest releases) but I found when trying to get _anyone_ who was interested in JALSE committing it was easier not to have it. We have unit testing, code coverage tools and travis CI builds - so I do care about quality. I just didn't want to make it more difficult than it had to be (as I can line by line comment a commit/pull-request anyway).
