### ISSUE TITLE
Gradle Wrapper

### ISSUE THREAD

**Issue by pbremer** [Ellzord/JALSE#77]
Just an idea, but I think we should use a gradle wrapper (gradlew). That way everybody has the same version of gradle now and forever. I would do it but last time I did it, the gradlew file for *NIX has MS line endings and it failed the build.

But all you have to do is:
In root of project directory run command: `gradle wrapper --version-gradle 2.x` (whatever version you want)

In the build.gradle file add:

```
task wrapper(type: Wrapper) {
    gradleVersion = '2.x' //Same version as the one in the command
}
```

To build:
`gradlew build`

**Comment by Ellzord** [comment]
http://gradle.org/docs/current/userguide/gradle_wrapper.html

`The Gradle Wrapper (henceforth referred to as the “wrapper”) is the preferred way of starting a Gradle build.`

Sounds good to me - Assigned

**Comment by Ellzord** [comment]
https://github.com/Ellzord/JALSE/commit/d8bf3255bd383b574a4759bc6d3a805b512e07ef

https://travis-ci.org/Ellzord/JALSE/builds/61821930
