### ISSUE TITLE
Should issues be more to a separate repo?

### ISSUE THREAD

**Issue by Ellzord** [Ellzord/JALSE#78]
I cannot assign anyone but those with push rights (doesn't suit the fork & pull request model): https://help.github.com/articles/issues-only-access-permissions/

If I create Ellzord/JALSE-Issues then I can assign out tickets and they can be managed by the individual. 

Also see https://github.com/blog/1439-closing-issues-across-repositories

**Comment by pbremer** [comment]
Personally, I do not think that is a good idea. A git repo is just for holding source code. 

Edit: An alternative, if you do not like github's issue tracking,  is having a bugzilla server

**Comment by Ellzord** [comment]
I guess for now we can stick with this until it becomes an issue

Bugzilla is an option - so is jira
